import type { Metadata } from "next";
import React from "react";
import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider"


export const metadata: Metadata = {
  title: "AcademyX",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <main>
        {children}
      </main>
      </body>
    </html>
  );
}
