import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Image from "next/image";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar" /*Importinh avatar from shadcn */
import Footerwave from "/public/Footer_Wave.svg"; /*Imporrting the wave svg */
import Logo from "/public/Academy-X-bg removed.svg";
import Search from "/public/Search-icon.svg";
import { Button } from "@/components/ui/button"
import GitHubLogo from "/public/icons8-github.svg";
import LinkedinLogo from "/public/icons8-linkedin.svg";
import MailLogo from "/public/icons8-mail-48.svg";
import WebsiteLogo from "/public/icons8-website-50.svg"

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "AcademyX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-slate-400">

        <header className="w-screen  h-1/6 flex   justify-around items-center border-academy bg-black  bg-opacity-0  border-4 rounded-b-sm border-t-0">
          
          
          
          <div className="    flex-shrink h-12 w-12 "> 
          </div>


          <div className="  flex-shrink">
            <a href="https://github.com/acmpesuecc/AcademyX">
            <Image src={Logo} alt="Logo" className="m-4"/>
                
            </a>
          </div>

      <div className="flex justify-start  items-start">
          <div className=" w-10 h-10"> <button ><Image src={Search} alt="Search icon"/></button></div>
          <div className=" " >
            <Avatar>
              <AvatarImage src="https://github.com/shadcn.png" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          </div>
          </div>




        </header>






        {children}
        
        <footer className="bottom-0 relative w-screen">
          <div className="flex justify-start relative z-0">
          <Image src={Footerwave} alt="Footerbg" className="w-screen"/>
          <div className="  flex flex-row  justify-items-end justify-between items-end  absolute bottom-0 z-10 w-screen h-3/5 ">

          <div className="w-fit h-fit"><p className="px-2">Webstie created by ACM PESU ECC <br />-this website is open source</p></div>

          <div className=" flex-shrink self-center">
            <a href="https://github.com/acmpesuecc/AcademyX">
            <Image src={Logo} alt="Logo" className="m-4"/>
                
            </a>
          </div>
          
            <div className=" z-20 text-xl  h-fit w-fit">
              <div className="  flex flex-row w-fit h-fit items-end justify-between">
                <Button variant="ghost" size="icon" className=" m-0.5"><a href="https://github.com/acmpesuecc/AcademyX" target="blank"><Image src={GitHubLogo} alt="Academy X Github"></Image></a></Button>
                <Button variant="ghost" size="icon" className=" m-0.5"><a href="https://github.com/acmpesuecc/AcademyX " target="blank" ><Image src={MailLogo} alt="ACM Mail"></Image></a></Button>
                <Button variant="ghost" size="icon" className=" m-0.5"><a href="https://www.linkedin.com/company/acm-pesu-ecc/" target="blank" ><Image src={LinkedinLogo} alt="ACM Linkedin"></Image></a></Button>
                <Button variant="ghost" size="icon" className=" m-0.5"><a href="https://acmpesuecc.github.io/index.html" target="blank" ><Image src={WebsiteLogo} alt="ACM Website"></Image></a></Button>
              </div>
              <p className=" text-center">&copy; ACMPESUECC</p>
              </div>
            </div>
          </div>
          
  </footer>
        
        </body>
    </html>
  );
}
